### ISSUE TITLE
cd pyqt-webengine && make failes because pkg-config is missing on OSX

### ISSUE THREAD

**Issue by svetlyak40wt** [atlas-engineer/next#267]
Full trace:

```
[+|art@art-osx:...ext/ports/pyqt-webengine]% make
make
pip3 install -r requirements.txt
Collecting pyqt5==5.12.2 (from -r requirements.txt (line 3))
  Downloading https://files.pythonhosted.org/packages/b8/05/0fd9de5eb664ad4c47047d857cd526576b7d45b3108fbb57ba64399be2d5/PyQt5-5.12.2-5.12.3-cp35.cp36.cp37.cp38-abi3-macosx_10_6_intel.whl (37.4MB)
     |████████████████████████████████| 37.4MB 132kB/s 
Collecting PyQtWebEngine (from -r requirements.txt (line 4))
  Downloading https://files.pythonhosted.org/packages/76/0f/4bb568ecffb260a15458c261ef61fcf3e791d00aeb65db5b057fcf0aa897/PyQtWebEngine-5.13.0-5.13.0-cp35.cp36.cp37.cp38-abi3-macosx_10_6_intel.whl (64.1MB)
     |████████████████████████████████| 64.1MB 150kB/s 
Collecting dbus-python (from -r requirements.txt (line 5))
  Downloading https://files.pythonhosted.org/packages/3f/e7/4edb582d1ffd5ac3c84188deea32e960b5c8c0fe1da56ce70224f85ce542/dbus-python-1.2.8.tar.gz (787kB)
     |████████████████████████████████| 788kB 45kB/s 
Collecting PyQt5_sip<13,>=4.19.14 (from pyqt5==5.12.2->-r requirements.txt (line 3))
  Downloading https://files.pythonhosted.org/packages/e3/a2/913dccc36827ee4be62a968273247a7f57fd1530060d33c5bd8fb66ce200/PyQt5_sip-4.19.18-cp37-cp37m-macosx_10_6_intel.whl (52kB)
     |████████████████████████████████| 61kB 358kB/s 
Building wheels for collected packages: dbus-python
  Building wheel for dbus-python (setup.py) ... error
  ERROR: Complete output from command /usr/local/opt/python/bin/python3.7 -u -c 'import setuptools, tokenize;__file__='"'"'/private/var/folders/_0/qrkydgy544l1hlhv8l6_t4t982z2bs/T/pip-install-2aorny8u/dbus-python/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /private/var/folders/_0/qrkydgy544l1hlhv8l6_t4t982z2bs/T/pip-wheel-89vhf_4o --python-tag cp37:
  ERROR: running bdist_wheel
  running build
  creating /private/var/folders/_0/qrkydgy544l1hlhv8l6_t4t982z2bs/T/pip-install-2aorny8u/dbus-python/build
  creating /private/var/folders/_0/qrkydgy544l1hlhv8l6_t4t982z2bs/T/pip-install-2aorny8u/dbus-python/build/temp.macosx-10.14-x86_64-3.7
  checking whether make supports nested variables... yes
  checking whether to enable maintainer-specific portions of Makefiles... no
  checking for gcc... gcc
  checking whether the C compiler works... yes
  checking for C compiler default output file name... a.out
  checking for suffix of executables...
  checking whether we are cross compiling... no
  checking for suffix of object files... o
  checking whether we are using the GNU C compiler... yes
  checking whether gcc accepts -g... yes
  checking for gcc option to accept ISO C89... none needed
  checking whether gcc understands -c and -o together... yes
  checking how to run the C preprocessor... gcc -E
  checking for grep that handles long lines and -e... /usr/bin/grep
  checking for egrep... /usr/bin/grep -E
  checking for ANSI C header files... yes
  checking for sys/types.h... yes
  checking for sys/stat.h... yes
  checking for stdlib.h... yes
  checking for string.h... yes
  checking for memory.h... yes
  checking for strings.h... yes
  checking for inttypes.h... yes
  checking for stdint.h... yes
  checking for unistd.h... yes
  checking minix/config.h usability... no
  checking minix/config.h presence... no
  checking for minix/config.h... no
  checking whether it is safe to define __EXTENSIONS__... yes
  checking for a BSD-compatible install... /usr/bin/install -c
  checking whether build environment is sane... yes
  checking for a thread-safe mkdir -p... /private/var/folders/_0/qrkydgy544l1hlhv8l6_t4t982z2bs/T/pip-install-2aorny8u/dbus-python/build-aux/install-sh -c -d
  checking for gawk... no
  checking for mawk... no
  checking for nawk... no
  checking for awk... awk
  checking whether make sets $(MAKE)... yes
  checking for style of include used by make... GNU
  checking whether UID '1345292665' is supported by ustar format... no
  checking whether GID '593637566' is supported by ustar format... no
  checking how to create a ustar tar archive... none
  checking dependency style of gcc... gcc3
  checking build system type... x86_64-apple-darwin18.5.0
  checking host system type... x86_64-apple-darwin18.5.0
  checking for native Windows host... no
  checking how to print strings... printf
  checking for a sed that does not truncate output... /usr/bin/sed
  checking for fgrep... /usr/bin/grep -F
  checking for ld used by gcc... /Library/Developer/CommandLineTools/usr/bin/ld
  checking if the linker (/Library/Developer/CommandLineTools/usr/bin/ld) is GNU ld... no
  checking for BSD- or MS-compatible name lister (nm)... /usr/bin/nm -B
  checking the name lister (/usr/bin/nm -B) interface... BSD nm
  checking whether ln -s works... yes
  checking the maximum length of command line arguments... 196608
  checking how to convert x86_64-apple-darwin18.5.0 file names to x86_64-apple-darwin18.5.0 format... func_convert_file_noop
  checking how to convert x86_64-apple-darwin18.5.0 file names to toolchain format... func_convert_file_noop
  checking for /Library/Developer/CommandLineTools/usr/bin/ld option to reload object files... -r
  checking for objdump... objdump
  checking how to recognize dependent libraries... pass_all
  checking for dlltool... no
  checking how to associate runtime and link libraries... printf %s\n
  checking for ar... ar
  checking for archiver @FILE support... no
  checking for strip... strip
  checking for ranlib... ranlib
  checking command to parse /usr/bin/nm -B output from gcc object... ok
  checking for sysroot... no
  checking for a working dd... /bin/dd
  checking how to truncate binary pipes... /bin/dd bs=4096 count=1
  checking for mt... no
  checking if : is a manifest tool... no
  checking for dsymutil... dsymutil
  checking for nmedit... nmedit
  checking for lipo... lipo
  checking for otool... otool
  checking for otool64... no
  checking for -single_module linker flag... yes
  checking for -exported_symbols_list linker flag... yes
  checking for -force_load linker flag... yes
  checking for dlfcn.h... yes
  checking for objdir... .libs
  checking if gcc supports -fno-rtti -fno-exceptions... yes
  checking for gcc option to produce PIC... -fno-common -DPIC
  checking if gcc PIC flag -fno-common -DPIC works... yes
  checking if gcc static flag -static works... no
  checking if gcc supports -c -o file.o... yes
  checking if gcc supports -c -o file.o... (cached) yes
  checking whether the gcc linker (/Library/Developer/CommandLineTools/usr/bin/ld) supports shared libraries... yes
  checking dynamic linker characteristics... darwin18.5.0 dyld
  checking how to hardcode library paths into programs... immediate
  checking whether stripping libraries is possible... yes
  checking if libtool supports shared libraries... yes
  checking whether to build shared libraries... yes
  checking whether to build static libraries... no
  checking for inline... inline
  checking for gawk... (cached) awk
  checking for python... /usr/local/opt/python/bin/python3.7
  checking for a version of Python >= '2.1.0'... yes
  checking for a version of Python >= '2.7'... yes
  checking for the distutils Python package... yes
  checking for Python include path... -I/usr/local/Cellar/python/3.7.4/Frameworks/Python.framework/Versions/3.7/include/python3.7m
  checking for Python library path... -L/usr/local/opt/python/Frameworks/Python.framework/Versions/3.7/lib -lpython3.7m
  checking for Python site-packages path... /usr/local/Cellar/python/3.7.4/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages
  checking python extra libraries... -ldl  -framework CoreFoundation
  checking python extra linking flags... -Wl,-stack_size,1000000  -framework CoreFoundation /usr/local/opt/python/Frameworks/Python.framework/Versions/3.7/Python
  checking consistency of all components of python development environment... yes
  checking for python version... 3.7
  checking for python platform... darwin
  checking for python script directory... ${prefix}/lib/python3.7/site-packages
  checking for python extension module directory... ${exec_prefix}/lib/python3.7/site-packages
  checking for git... /usr/bin/git
  checking python3.7 module: sphinx... no
  checking python3.7 module: sphinx_rtd_theme... no
  checking for dbus-run-session... dbus-run-session
  checking for pkg-config... no
  checking for DBUS... no
  configure: error: in `/private/var/folders/_0/qrkydgy544l1hlhv8l6_t4t982z2bs/T/pip-install-2aorny8u/dbus-python/build/temp.macosx-10.14-x86_64-3.7':
  configure: error: The pkg-config script could not be found or is too old.  Make sure it
  is in your PATH or set the PKG_CONFIG environment variable to the full
  path to pkg-config.
  
  Alternatively, you may set the environment variables DBUS_CFLAGS
  and DBUS_LIBS to avoid the need to call pkg-config.
  See the pkg-config man page for more details.
  
  To get pkg-config, see <http://pkg-config.freedesktop.org/>.
  See `config.log' for more details
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/private/var/folders/_0/qrkydgy544l1hlhv8l6_t4t982z2bs/T/pip-install-2aorny8u/dbus-python/setup.py", line 109, in <module>
      tests_require=['tap.py'],
    File "/usr/local/lib/python3.7/site-packages/setuptools/__init__.py", line 145, in setup
      return distutils.core.setup(**attrs)
    File "/usr/local/Cellar/python/3.7.4/Frameworks/Python.framework/Versions/3.7/lib/python3.7/distutils/core.py", line 148, in setup
      dist.run_commands()
    File "/usr/local/Cellar/python/3.7.4/Frameworks/Python.framework/Versions/3.7/lib/python3.7/distutils/dist.py", line 966, in run_commands
      self.run_command(cmd)
    File "/usr/local/Cellar/python/3.7.4/Frameworks/Python.framework/Versions/3.7/lib/python3.7/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/usr/local/lib/python3.7/site-packages/wheel/bdist_wheel.py", line 192, in run
      self.run_command('build')
    File "/usr/local/Cellar/python/3.7.4/Frameworks/Python.framework/Versions/3.7/lib/python3.7/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/usr/local/Cellar/python/3.7.4/Frameworks/Python.framework/Versions/3.7/lib/python3.7/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/private/var/folders/_0/qrkydgy544l1hlhv8l6_t4t982z2bs/T/pip-install-2aorny8u/dbus-python/setup.py", line 62, in run
      cwd=builddir)
    File "/usr/local/Cellar/python/3.7.4/Frameworks/Python.framework/Versions/3.7/lib/python3.7/subprocess.py", line 347, in check_call
      raise CalledProcessError(retcode, cmd)
  subprocess.CalledProcessError: Command '['/private/var/folders/_0/qrkydgy544l1hlhv8l6_t4t982z2bs/T/pip-install-2aorny8u/dbus-python/configure', '--disable-maintainer-mode', 'PYTHON=/usr/local/opt/python/bin/python3.7', '--prefix=/private/var/folders/_0/qrkydgy544l1hlhv8l6_t4t982z2bs/T/pip-install-2aorny8u/dbus-python/build/temp.macosx-10.14-x86_64-3.7/prefix']' returned non-zero exit status 1.
  ----------------------------------------
  ERROR: Failed building wheel for dbus-python
  Running setup.py clean for dbus-python
Failed to build dbus-python
ERROR: pyqtwebengine 5.13.0 has requirement PyQt5>=5.13, but you'll have pyqt5 5.12.2 which is incompatible.
Installing collected packages: PyQt5-sip, pyqt5, PyQtWebEngine, dbus-python
  Running setup.py install for dbus-python ... error
    ERROR: Complete output from command /usr/local/opt/python/bin/python3.7 -u -c 'import setuptools, tokenize;__file__='"'"'/private/var/folders/_0/qrkydgy544l1hlhv8l6_t4t982z2bs/T/pip-install-2aorny8u/dbus-python/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/_0/qrkydgy544l1hlhv8l6_t4t982z2bs/T/pip-record-_oaeqf2h/install-record.txt --single-version-externally-managed --compile:
    ERROR: running install
    running build
    creating /private/var/folders/_0/qrkydgy544l1hlhv8l6_t4t982z2bs/T/pip-install-2aorny8u/dbus-python/build
    creating /private/var/folders/_0/qrkydgy544l1hlhv8l6_t4t982z2bs/T/pip-install-2aorny8u/dbus-python/build/temp.macosx-10.14-x86_64-3.7
    checking whether make supports nested variables... yes
    checking whether to enable maintainer-specific portions of Makefiles... no
    checking for gcc... gcc
    checking whether the C compiler works... yes
    checking for C compiler default output file name... a.out
    checking for suffix of executables...
    checking whether we are cross compiling... no
    checking for suffix of object files... o
    checking whether we are using the GNU C compiler... yes
    checking whether gcc accepts -g... yes
    checking for gcc option to accept ISO C89... none needed
    checking whether gcc understands -c and -o together... yes
    checking how to run the C preprocessor... gcc -E
    checking for grep that handles long lines and -e... /usr/bin/grep
    checking for egrep... /usr/bin/grep -E
    checking for ANSI C header files... yes
    checking for sys/types.h... yes
    checking for sys/stat.h... yes
    checking for stdlib.h... yes
    checking for string.h... yes
    checking for memory.h... yes
    checking for strings.h... yes
    checking for inttypes.h... yes
    checking for stdint.h... yes
    checking for unistd.h... yes
    checking minix/config.h usability... no
    checking minix/config.h presence... no
    checking for minix/config.h... no
    checking whether it is safe to define __EXTENSIONS__... yes
    checking for a BSD-compatible install... /usr/bin/install -c
    checking whether build environment is sane... yes
    checking for a thread-safe mkdir -p... /private/var/folders/_0/qrkydgy544l1hlhv8l6_t4t982z2bs/T/pip-install-2aorny8u/dbus-python/build-aux/install-sh -c -d
    checking for gawk... no
    checking for mawk... no
    checking for nawk... no
    checking for awk... awk
    checking whether make sets $(MAKE)... yes
    checking for style of include used by make... GNU
    checking whether UID '1345292665' is supported by ustar format... no
    checking whether GID '593637566' is supported by ustar format... no
    checking how to create a ustar tar archive... none
    checking dependency style of gcc... gcc3
    checking build system type... x86_64-apple-darwin18.5.0
    checking host system type... x86_64-apple-darwin18.5.0
    checking for native Windows host... no
    checking how to print strings... printf
    checking for a sed that does not truncate output... /usr/bin/sed
    checking for fgrep... /usr/bin/grep -F
    checking for ld used by gcc... /Library/Developer/CommandLineTools/usr/bin/ld
    checking if the linker (/Library/Developer/CommandLineTools/usr/bin/ld) is GNU ld... no
    checking for BSD- or MS-compatible name lister (nm)... /usr/bin/nm -B
    checking the name lister (/usr/bin/nm -B) interface... BSD nm
    checking whether ln -s works... yes
    checking the maximum length of command line arguments... 196608
    checking how to convert x86_64-apple-darwin18.5.0 file names to x86_64-apple-darwin18.5.0 format... func_convert_file_noop
    checking how to convert x86_64-apple-darwin18.5.0 file names to toolchain format... func_convert_file_noop
    checking for /Library/Developer/CommandLineTools/usr/bin/ld option to reload object files... -r
    checking for objdump... objdump
    checking how to recognize dependent libraries... pass_all
    checking for dlltool... no
    checking how to associate runtime and link libraries... printf %s\n
    checking for ar... ar
    checking for archiver @FILE support... no
    checking for strip... strip
    checking for ranlib... ranlib
    checking command to parse /usr/bin/nm -B output from gcc object... ok
    checking for sysroot... no
    checking for a working dd... /bin/dd
    checking how to truncate binary pipes... /bin/dd bs=4096 count=1
    checking for mt... no
    checking if : is a manifest tool... no
    checking for dsymutil... dsymutil
    checking for nmedit... nmedit
    checking for lipo... lipo
    checking for otool... otool
    checking for otool64... no
    checking for -single_module linker flag... yes
    checking for -exported_symbols_list linker flag... yes
    checking for -force_load linker flag... yes
    checking for dlfcn.h... yes
    checking for objdir... .libs
    checking if gcc supports -fno-rtti -fno-exceptions... yes
    checking for gcc option to produce PIC... -fno-common -DPIC
    checking if gcc PIC flag -fno-common -DPIC works... yes
    checking if gcc static flag -static works... no
    checking if gcc supports -c -o file.o... yes
    checking if gcc supports -c -o file.o... (cached) yes
    checking whether the gcc linker (/Library/Developer/CommandLineTools/usr/bin/ld) supports shared libraries... yes
    checking dynamic linker characteristics... darwin18.5.0 dyld
    checking how to hardcode library paths into programs... immediate
    checking whether stripping libraries is possible... yes
    checking if libtool supports shared libraries... yes
    checking whether to build shared libraries... yes
    checking whether to build static libraries... no
    checking for inline... inline
    checking for gawk... (cached) awk
    checking for python... /usr/local/opt/python/bin/python3.7
    checking for a version of Python >= '2.1.0'... yes
    checking for a version of Python >= '2.7'... yes
    checking for the distutils Python package... yes
    checking for Python include path... -I/usr/local/Cellar/python/3.7.4/Frameworks/Python.framework/Versions/3.7/include/python3.7m
    checking for Python library path... -L/usr/local/opt/python/Frameworks/Python.framework/Versions/3.7/lib -lpython3.7m
    checking for Python site-packages path... /usr/local/Cellar/python/3.7.4/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages
    checking python extra libraries... -ldl  -framework CoreFoundation
    checking python extra linking flags... -Wl,-stack_size,1000000  -framework CoreFoundation /usr/local/opt/python/Frameworks/Python.framework/Versions/3.7/Python
    checking consistency of all components of python development environment... yes
    checking for python version... 3.7
    checking for python platform... darwin
    checking for python script directory... ${prefix}/lib/python3.7/site-packages
    checking for python extension module directory... ${exec_prefix}/lib/python3.7/site-packages
    checking for git... /usr/bin/git
    checking python3.7 module: sphinx... no
    checking python3.7 module: sphinx_rtd_theme... no
    checking for dbus-run-session... dbus-run-session
    checking for pkg-config... no
    checking for DBUS... no
    configure: error: in `/private/var/folders/_0/qrkydgy544l1hlhv8l6_t4t982z2bs/T/pip-install-2aorny8u/dbus-python/build/temp.macosx-10.14-x86_64-3.7':
    configure: error: The pkg-config script could not be found or is too old.  Make sure it
    is in your PATH or set the PKG_CONFIG environment variable to the full
    path to pkg-config.
    
    Alternatively, you may set the environment variables DBUS_CFLAGS
    and DBUS_LIBS to avoid the need to call pkg-config.
    See the pkg-config man page for more details.
    
    To get pkg-config, see <http://pkg-config.freedesktop.org/>.
    See `config.log' for more details
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/_0/qrkydgy544l1hlhv8l6_t4t982z2bs/T/pip-install-2aorny8u/dbus-python/setup.py", line 109, in <module>
        tests_require=['tap.py'],
      File "/usr/local/lib/python3.7/site-packages/setuptools/__init__.py", line 145, in setup
        return distutils.core.setup(**attrs)
      File "/usr/local/Cellar/python/3.7.4/Frameworks/Python.framework/Versions/3.7/lib/python3.7/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/usr/local/Cellar/python/3.7.4/Frameworks/Python.framework/Versions/3.7/lib/python3.7/distutils/dist.py", line 966, in run_commands
        self.run_command(cmd)
      File "/usr/local/Cellar/python/3.7.4/Frameworks/Python.framework/Versions/3.7/lib/python3.7/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/usr/local/lib/python3.7/site-packages/setuptools/command/install.py", line 61, in run
        return orig.install.run(self)
      File "/usr/local/Cellar/python/3.7.4/Frameworks/Python.framework/Versions/3.7/lib/python3.7/distutils/command/install.py", line 545, in run
        self.run_command('build')
      File "/usr/local/Cellar/python/3.7.4/Frameworks/Python.framework/Versions/3.7/lib/python3.7/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/local/Cellar/python/3.7.4/Frameworks/Python.framework/Versions/3.7/lib/python3.7/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/private/var/folders/_0/qrkydgy544l1hlhv8l6_t4t982z2bs/T/pip-install-2aorny8u/dbus-python/setup.py", line 62, in run
        cwd=builddir)
      File "/usr/local/Cellar/python/3.7.4/Frameworks/Python.framework/Versions/3.7/lib/python3.7/subprocess.py", line 347, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command '['/private/var/folders/_0/qrkydgy544l1hlhv8l6_t4t982z2bs/T/pip-install-2aorny8u/dbus-python/configure', '--disable-maintainer-mode', 'PYTHON=/usr/local/opt/python/bin/python3.7', '--prefix=/private/var/folders/_0/qrkydgy544l1hlhv8l6_t4t982z2bs/T/pip-install-2aorny8u/dbus-python/build/temp.macosx-10.14-x86_64-3.7/prefix']' returned non-zero exit status 1.
    ----------------------------------------
ERROR: Command "/usr/local/opt/python/bin/python3.7 -u -c 'import setuptools, tokenize;__file__='"'"'/private/var/folders/_0/qrkydgy544l1hlhv8l6_t4t982z2bs/T/pip-install-2aorny8u/dbus-python/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/_0/qrkydgy544l1hlhv8l6_t4t982z2bs/T/pip-record-_oaeqf2h/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /private/var/folders/_0/qrkydgy544l1hlhv8l6_t4t982z2bs/T/pip-install-2aorny8u/dbus-python/
make: *** [install] Error 1
```

**Comment by svetlyak40wt** [comment]
Installed with brew:

    brew install pkg-config

**Comment by svetlyak40wt** [comment]
Another error appeared in the log:

```
  checking for git... /usr/bin/git
  checking python3.7 module: sphinx... no
  checking python3.7 module: sphinx_rtd_theme... no
  checking for dbus-run-session... dbus-run-session
  checking for pkg-config... /usr/local/bin/pkg-config
  checking pkg-config is at least version 0.9.0... yes
  checking for DBUS... no
  configure: error: Package requirements (dbus-1 >= 1.8) were not met:
  
  No package 'dbus-1' found
  
  Consider adjusting the PKG_CONFIG_PATH environment variable if you
  installed software in a non-standard prefix.
  
  Alternatively, you may set the environment variables DBUS_CFLAGS
  and DBUS_LIBS to avoid the need to call pkg-config.
  See the pkg-config man page for more details.

```

**Comment by svetlyak40wt** [comment]
Installed with

    brew install dbus

**Comment by svetlyak40wt** [comment]
Now make passed successfully:

```
make
pip3 install -r requirements.txt
Requirement already satisfied: pyqt5==5.12.2 in /usr/local/lib/python3.7/site-packages (from -r requirements.txt (line 3)) (5.12.2)
Requirement already satisfied: PyQtWebEngine in /usr/local/lib/python3.7/site-packages (from -r requirements.txt (line 4)) (5.13.0)
Requirement already satisfied: dbus-python in /usr/local/lib/python3.7/site-packages (from -r requirements.txt (line 5)) (1.2.8)
Requirement already satisfied: PyQt5_sip<13,>=4.19.14 in /usr/local/lib/python3.7/site-packages (from pyqt5==5.12.2->-r requirements.txt (line 3)) (4.19.18)

```

**Comment by vindarel** [comment]
Thanks for testing this branch, specially in MacOS. We are finalizing the PyQt port right now, so we appreciate the input (specially John on MacOS), and be aware that things change in this branch.

**Comment by svetlyak40wt** [comment]
But now `make run` does not work:

```
make run
python3 next-pyqt.py
Traceback (most recent call last):
  File "next-pyqt.py", line 3, in <module>
    import utility
  File "/Users/art/projects/lisp/next/ports/pyqt-webengine/utility.py", line 4, in <module>
    import window
  File "/Users/art/projects/lisp/next/ports/pyqt-webengine/window.py", line 3, in <module>
    import buffers
  File "/Users/art/projects/lisp/next/ports/pyqt-webengine/buffers.py", line 6, in <module>
    from PyQt5.QtWebEngineWidgets import QWebEngineProfile, QWebEngineView
ImportError: dlopen(/usr/local/lib/python3.7/site-packages/PyQt5/QtWebEngineWidgets.so, 2): Library not loaded: @rpath/QtQuick.framework/Versions/5/QtQuick
  Referenced from: /usr/local/lib/python3.7/site-packages/PyQt5/QtWebEngineWidgets.so
  Reason: Incompatible library version: QtWebEngineWidgets.so requires version 5.13.0 or later, but QtQuick provides version 5.12.0
make: *** [run] Error 1
```

**Comment by vindarel** [comment]
And if you 

   pip3 install "PyQtWebEngine==5.13" 

? We need version 5.12 or higher.
